requires = ["tox>=4.19"]
env_list = ["lint", "test"]

[env.lint]
description = "runs linter ruff"
deps = [
    "ruff>=0.14"
]
commands = [["ruff", "check"]]

[env.test]
description = "install pytest in a virtual environment and invoke it on the tests folder"
package = "editable"
deps = [
    "click>=8.3.0",
    "gitpython>=3.1.45",
    "pytest>=8.4.2",
    "jinja2>=3.1",
    "requests>=2.31",
    "types-requests>=2.32.4.20250913",
    "markdown>=3.5",
    "python-dotenv>=1.0.1",
]
commands = [["pytest", "tests"]]
