requires = ["tox>=4.19"]
env_list = ["lint", "test"]

[env.lint]
description = "runs linter ruff"
deps = [
    "ruff>=0.14"
]
commands = [["ruff", "check"]]

[env.test]
description = "install pytest in a virtual environment and invoke it on the tests folder"
package = "editable"
deps = [
    "pytest>=8",
    "pytest-sugar>=1",
    "jinja2>=3.1",
    "click>=8.3",
    "requests>=2.31"
]
commands = [["pytest", "tests"]]
